[package]
name = "pinger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.26"
influxdb = { version = "0.7.0", features = ["derive"] }
ping-rs = "0.1.2"
tokio = { version = "1.29.1", features =["full"] }
